config/routes.rb
Rails.application.routes.draw do
  

  get 'comments/index'

  get 'comments/new'

  get 'comments/show'

  get 'comments/edit'

  devise_for :users
  resources :users, only: [:update, :show, :index]
  
  resources :advertisements 

  resources :topics do
    resources :posts, except: [:index], controller: 'topics/posts'
  end

  resources :posts, only: [:index] do
    resources :comments, only: [:create, :destroy]
      resources :favorites, only: [:create, :destroy]

      post '/up-vote' => 'votes#up_vote', as: :up_vote
      post '/down-vote' => 'votes#down_vote', as: :down_vote

  end

  get 'about' => 'welcome#about'

  root to: 'welcome#index'

end

app/models/summary.rb
# == Schema Information
#
# Table name: summaries
#
#  id         :integer          not null, primary key
#  body       :text
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  post_id    :integer
#

class Summary < ActiveRecord::Base
  belongs_to :post
end

app/controllers/summaries_controller.rb
class SummariesController < ApplicationController
  
  def index
    @summaries = Summary.all
    authorize @summaries
  end

  def new
    @summary = Summary.new
    authorize @summary
  end

  def show
    @summary = Summary.find(params[:id])
    @post = @summary.post
    authorize @summary
  end

  def edit
    @summary = Summary.find(params[:id])
    authorize @summary
  end

  def create
    @summary = Summary.new(params.require(:summary).permit(:name, :body))
    authorize @summary
    if @summary.save
      redirect_to @summary, notice: "Summary was saved successfully"
    else
      flash[:error] = "Error creating summary. Please try again."
      render :new
    end
  end

  def update
    @summary = Summary.find(params[:id])
    authorize @summary
    if @summary.update_attributes(params.require(:summary).permit(:name, :body))
      redirect_to @summary
    else
      flash[:error] = "Error saving summary. Please try again."
      render :edit
    end
  end
end

app/helpers/summaries_helper.rb
module SummariesHelper
end

app/views/summaries/_summary_fields.html.erb
<%= f.label :body %>
<%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter summary" %>

 

app/views/summaries/edit.html.erb
 <h1>Edit Summary</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for summaries:</p>
     <ul>
       <li>Make sure the summary is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @summary do |s| %>
       <div class="form-group">
         <%= s.label :name %>
         <%= s.text_field :name, class: 'form-control', placeholder: "Enter topic name" %>
       </div>
       <div class="form-group">
         <%= s.label :body %>
         <%= s.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter summary" %>
       </div>
       <%= f.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/summaries/index.html.erb
<h1>Summaries</h1>  

<div class="row">
  <div class="col-md-8">
    <% @summaries.each do |summary| %>
      <div class="media">
        <div class="media-body">
          <h4 class="media-heading">
            <%= link_to summary.post.title, [summary.post.topic, summary.post] %>
          </h4>
          <small>
            <%= summary.body %>
          </small>
        </div>
      </div>
    <% end %>
  </div>
  <div class="col-md-4">
  </div>
</div>

app/views/summaries/new.html.erb
<h1>New Summary</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for summaries:</p>
     <ul>
       <li>Make sure the summary is appropriate.</li>
       <li>Never insult dogs.</li>
       <li>Smile when you type.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= form_for @summary do |s| %>
       <div class="form-group">
         <%= s.label :name %>
         <%= s.text_field :name, class: 'form-control', placeholder: "Enter summary name" %>
       </div>
       <div class="form-group">
         <%= s.label :body%>
         <%= s.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter summary" %>
       </div>
       <%= s.submit "Save", class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>

app/views/summaries/show.html.erb
 <h1><%= @summary.name %></h1>
 
 <% if policy(@summary).update? %>
   <%= link_to "Edit Summary", edit_summary_path, class: 'btn btn-success' %>
 <% end %>
 
 <div class="row">
   <div class="col-md-8">
     <p class="lead"><%= @summary.body %></p>

       <div class="media">
         <div class="media-body">
           <h4 class="media-heading">
             <%= link_to @post.title, topic_post_path(@post.topic, @post) %>
           </h4>
         </div>
       </div>

   </div>
   <div class="col-md-4">
     <% if policy(Post.new).create? %>
       <%= link_to "New Post", new_post_path(@topic), class: 'btn btn-success' %>
     <% end %>
   </div>
 </div>